# https://espanso.org/docs/configuration/app-specific-configurations/#advanced-use-cases-for-filter_title
# ------------------------------------------------------------------------------
# only activates code snippets when a file of the right language is open

filter_title: .sh$|^\.z|Terminal|Alacritty

extra_includes:
  - "../match/_shell.yml"
