# https://github.com/toml-lang/toml
# https://starship.rs/config/
# ----------------------------------

# prompt in general
add_newline = false
continuation_prompt = "▶▶"
format = "[$directory$custom$git_branch$git_status$git_metrics$git_commit$git_state](bg:#393D4F)$cmd_duration$status$character"
right_format="$package$nodejs$python$jobs$memory_usage"

[character]
success_symbol = " [◈](bold green)"
error_symbol = " [◈](bold red)"
# ❱

[cmd_duration]
min_time = 3000
format = " [◷ $duration](bold yellow)"
# ◴◵◶◷

[memory_usage]
disabled = false
symbol = "◕"
threshold = 70
format = " [$symbol$ram_pct]($style)"

[directory]
style = "bold fg:#9AEDFE bg:#393D4F"
truncation_length = 2
truncation_symbol = "/"
truncate_to_repo = true
read_only = "⛔️"
format = "[$path $read_only]($style)"

[directory.substitutions]
"~/Library/Mobile Documents/iCloud~md~obsidian/Documents/" = "/iCloud-Obsidian"
"~/Library/Mobile Documents/com~apple~CloudDocs" = "~/iCloud"
"Dokumente/IT Backups/Alfred.alfredpreferences" = "AlfredPrefs"
"user.workflow.765354AA-49F0-4CB1-8DB0-EA4BE2DB09F8" = "PDF Annotation Extractor"
"user.workflow.D02FCDA1-EA32-4486-B5A6-09B42C44677C" = "Shimmering Obsidian"
"user.workflow.41B90DCD-A99E-4943-A19A-E91859557FB0" = "Pandoc-Suite"

[status]
format = " [$symbol$status]($style)"
disabled = false
symbol = "⚡"

[sudo]
format="[sudo $symbol]($style)"
disabled = false
symbol = "♠︎"

[jobs]
symbol = "Jobs"
format = "[ +$number $symbol ]($style)"
style = "fg:white bg:bright-black"
symbol_threshold = 1
number_threshold = 1

# mostly conflicts
[git_state]
style = 'fg:#FFBF72 bg:#393D4F'

[git_commit]
style = "fg:yellow bg:#393D4F"

# branch
[git_branch]
only_attached = true
symbol = ""
style = "bold fg:141 bg:#393D4F"
format = "[$symbol$branch]($style) "

# files
[git_status]
untracked = '[+$count ](fg:green bg:#393D4F)'
deleted = '[-$count ](fg:red bg:#393D4F)'
modified = '[*$count ](fg:yellow bg:#393D4F)'
renamed = '[✎$count ](fg:yellow bg:#393D4F)'
staged = '[◼︎$count ](fg:#FFBF72 bg:#393D4F)'
conflicted = '[⤱$count ](fg:red bg:#393D4F)'
diverged = '[⇈$count ](fg:#FFBF72 bg:#393D4F)'
ahead = '[⇡$count ](fg:#FFBF72 bg:#393D4F)'
behind = '[⇣$count ](fg:yellow bg:#393D4F)'
format = '[$ahead_behind$conflicted$stashed$deleted$staged$untracked$renamed$modified](bold fg:purple bg:#393D4F)'

# lines
# conditional display block needed https://github.com/starship/starship/issues/3253
[git_metrics]
disabled = false
added_style = "fg:green bg:#393D4F"
deleted_style = "fg:red bg:#393D4F"
format = '(\([+$added]($added_style)/[-$deleted]($deleted_style)\))'

[package]
format = "[$symbol$version]($style)"
version_format = "v${raw}"
symbol = ""
style = "dimmed 208"

[nodejs]
format = " [$symbol$version]($style)"
version_format = "$major"
style = "dimmed 73"
detect_extensions = ["ts"]

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = "$major.$minor"
style = "dimmed yellow"
python_binary = ["python3"]

[custom.file_number]
command = "ls | wc -l"
when = "true" # run always, needs to use the `true` command
style = "bold fg:blue bg:#393D4F"
format = "\($output)"
