# https://starship.rs/config/ ----> https://github.com/toml-lang/toml
# Ansi colors: https://i.stack.imgur.com/KTSQa.png
# nerd font icons https://www.nerdfonts.com/cheat-sheet

# --------------------------------------------------
# Terminus does not properly support bold, therefore
# separate config file for it
# --------------------------------------------------

# prompt in general
add_newline = false
continuation_prompt = "❯"
format = "[$directory${custom.folder_number}${custom.file_number}$git_branch$git_status$git_metrics$git_commit$git_state](bg:black)[](black)$cmd_duration$status$character"
right_format="$package${custom.alfred}$nodejs$python$jobs$memory_usage"

[character]
# "⏼⏻⟐"
success_symbol = " [⟐](bold green)"
error_symbol = " [](bold red)" # terminus needs extra space

[cmd_duration]
min_time = 2500
format = " [ $duration](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "/"
truncate_to_repo = true
read_only = "ﮖ  "
read_only_style = "red bg:black"
style = "fg:bright-blue bg:black bold" # terminus different
format = "[$path]($style) [$read_only]($read_only_style)"

[directory.substitutions]
"/Library/Mobile Documents/iCloud~md~obsidian/Documents" = "/ "
"/Library/Mobile Documents/com~apple~CloudDocs" = "/ "
"/File Hub" = "/ "
"Configs/Alfred.alfredpreferences/workflows" = "AlfredPrefs"
"user.workflow.765354AA-49F0-4CB1-8DB0-EA4BE2DB09F8" = "PDF Annotation Extractor"
"user.workflow.D02FCDA1-EA32-4486-B5A6-09B42C44677C" = "Shimmering Obsidian"
"user.workflow.41B90DCD-A99E-4943-A19A-E91859557FB0" = "Supercharged Citation Picker"

[custom.file_number]
command = "find . -maxdepth 1 -type f -not -name '.DS_Store' | wc -l"
when = "true" # run always
symbol = " "
description = "Number of files in the current working directory"
format = '[$symbol$output]($style) '
style = "fg:yellow bg:black bold" # terminus different

[custom.folder_number]
command = "find . -maxdepth 1 -type d -not -name '.git' -not -name '.' | wc -l"
when = "true"
symbol = " "
description = "Number of folders in the current working directory"
format = '[$symbol$output]($style) '
style = "fg:yellow bg:black bold" # terminus different

[status]
format = " [$symbol$status]($style)"
disabled = false
symbol = ""

[sudo]
format="[sudo $symbol]($style)"
disabled = false

# -------------
# git
# -------------

[git_state] # mostly conflicts
style = 'fg:blue bg:black'

[git_commit]
style = "fg:yellow bg:black"

# branch
[git_branch]
only_attached = true
symbol = ""
style = "fg:purple bg:black bold" # terminus different
format = "[$symbol$branch]($style) "

# files
[git_status]
untracked = '[+$count ](fg:green bg:black)'
deleted = '[-$count ](fg:red bg:black)'
modified = '[*$count ](fg:cyan bg:black)'
renamed = '[✎$count ](fg:blue bg:black)'
staged = '[◎$count ](fg:cyan bg:black)'
conflicted = '[⤱$count ](fg:red bg:black)'
diverged = '[⇈$count ](fg:cyan bg:black)'
ahead = '[⇡$count ](fg:cyan bg:black)'
behind = '[⇣$count ](fg:yellow bg:black)'
style = 'fg:purple bg:black bold' # terminus different
format = '[$ahead_behind$conflicted$stashed$staged$untracked$renamed$modified$deleted]($style)'

# lines
[git_metrics]
disabled = false
added_style = "fg:green bg:black"
deleted_style = "fg:red bg:black"
format = '([\(](dimmed bg:black)[+$added]($added_style)[/](dimmed bg:black)[-$deleted]($deleted_style)[\)](dimmed bg:black))'

# -------------
# right side
# -------------
[jobs]
symbol = ""
format = "[ +$number $symbol ]($style)"
style = "fg:white"
symbol_threshold = 1
number_threshold = 2

[memory_usage]
disabled = false
symbol = " "
threshold = 75
format = " [$symbol$ram_pct]($style)"

[package]
format = "[$symbol$version]($style)"
version_format = "$raw"
symbol = " "
style = "dimmed 208"

[custom.alfred]
files = ["info.plist"]
command = "plutil -extract version xml1 -o - info.plist | sed -n 4p | cut -d'>' -f2 | cut -d'<' -f1"
symbol = " "
os = "macos"
description = "Version number of Alfred Workflow"
style = "dimmed 208"
format = '[Alfred](purple) [$symbol$output]($style)'

[nodejs]
format = " [$symbol$version]($style)"
version_format = "$major"
style = "dimmed cyan"
detect_extensions = ["ts"] # dont trigger for JXA

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = "$major.$minor"
style = "dimmed yellow"
python_binary = ["python3"]
symbol = " "

